module.exports = `
  type User {
    _id: String
    name: String
    email: String
    jwt: String
  }

  type Query {
    getAllUsers: [User]
  }

  type Mutation {
      addUser(
        name: String!
        email: String!
      ):User

      updateUser(
        _id: String!
        name: String
        email: String
      ): User

      deleteUser(
        _id: String!
      ): User
      register(email:String!, password:String!,name:String!):User
      login(email:String!, password:String! ):User
    }
`
